Products =[
    {
        'id': '1',
        'name': "LEOTUDE Women's Oversized Cottonblend Half Sleeve Drop Shoulder Tshirt",
        'image': '../../images/tshirt/acc.jpg' ,
        'description':" L will fit you best based on data from customers who buy the same sizes as you. Care Instructions: Hand Wash Only Fit Type: Oversized Fit Neck Style: Round Sleeve Type: Half Sleeve Pattern : Printed Color : Brown Fit Type: Oversized ",
        'brand': "LEOTUDE",
        'categroy': "Tshirt" ,
        'price': '1099' ,
        'countInStock': '12',
        'rating': '3.8',
        'numberReviews': '275',

    },
    {
        'id': '2',
        'name': "Veirdo White Oversized Cotton Crew Neck T-Shirt with Chest Print for Men ",
        'image': '../../images/tshirt/ts_2.1.jpg' ,
        'description':" Care Instructions: Hand Wash Only Fit Type: Oversized Fit  Fabric: Cotton  Neckline: Crew Neck  Sleeves: Half-slevees More comfortable for your classic everyday look.",
        'brand': "Veirdo",
        'categroy': "Tshirt" ,
        'price': '1199' ,
        'countInStock': '10',
        'rating': '3.6',
        'numberReviews': '156',

    },
    {
        'id': '3',
        'name': "EYEBOGLER Mens Cotton Regular Fit T-Shirt Grey",
        'image': '../../images/tshirt/ts_3.1.jpg' ,
        'description':" Care Instructions: Hand Wash Only Fit Type: Regular Fit Breathable Cotton Fabric",
        'brand': "EYEBOGLER",
        'categroy': "Tshirt" ,
        'price': '1299' ,
        'countInStock': '21',
        'rating': '3.2',
        'numberReviews': '111',

    },
    {
        'id': '4',
        'name': "Veirdo® Oversized Loose Baggy Fit Drop Shooulder Half Sleeves Pure Cotton Will Never Die Graphic Printed T-Shirt for Men",
        'image': '../../images/tshirt/ts_4.1.jpg' ,
        'description':"Care Instructions: Hand Wash Only Fit Type: Oversized Fit Fabric: Cotton Neckline: Crew Neck Sleeves: Half-slevees More comfortable for your classic everyday look.",
        'brand': "Veirdo",
        'categroy': "Tshirt" ,
        'price': '1199' ,
        'countInStock': '10',
        'rating': '4.0',
        'numberReviews': '134',

    },
    {
        'id': '5',
        'name': "Van Heusen Athleisure Men Polo T-Shirt - 100% Combed Cotton - Colour Fresh, Quick Dry, Ultra Soft",
        'image': '../../images/tshirt/ts_5.1.jpg' ,
        'description':"Care Instructions: Machine Wash Fit Type: Regular Fit Colour Fresh: The Colour Fresh technology keeps the fabric looking new for longer. Lab tested. Wicking: The fabric has wicking property which draws perspiration from the skin keeping the body cool, dry and comfortable. Ultra Soft: The fabric is extremely soft and comfortable, keeping you at ease for hours. 100% Combed Cotton: The combed cotton fabric construction makes the polo t-shirt super soft while improving the durability and breathability. Slim Fit: The polo t-shirt is framed in a Slim Fit that adds a sleek look while keeping you at ease. Pattern Type: Solid; Occasion Type: Casual; Lifestyle: Casual; Sleeve Type: Half Sleeve; Fit Type: Regular Fit; Sport Type: Golf",
        'brand': "Van Heusen",
        'categroy': "Tshirt" ,
        'price': '1149',
        'countInStock': '4',
        'rating': '4.0',
        'numberReviews': '1825',

    },
    {
        'id': '6',
        'name': "LEOTUDE Women's Oversized Cottonblend Half Sleeve Drop Shoulder Tshirt",
        'image': '../../images/tshirt/acc.jpg' ,
        'description':" L will fit you best based on data from customers who buy the same sizes as you. Care Instructions: Hand Wash Only Fit Type: Oversized Fit Neck Style: Round Sleeve Type: Half Sleeve Pattern : Printed Color : Brown Fit Type: Oversized ",
        'brand': "LEOTUDE",
        'categroy': "Tshirt" ,
        'price': '1099' ,
        'countInStock': '12',
        'rating': '3.8',
        'numberReviews': '275',

    },
    {
        'id': '7',
        'name': "Veirdo White Oversized Cotton Crew Neck T-Shirt with Chest Print for Men ",
        'image': '../../images/tshirt/ts_2.1.jpg' ,
        'description':" Care Instructions: Hand Wash Only Fit Type: Oversized Fit  Fabric: Cotton  Neckline: Crew Neck  Sleeves: Half-slevees More comfortable for your classic everyday look.",
        'brand': "Veirdo",
        'categroy': "Tshirt" ,
        'price': '1199' ,
        'countInStock': '10',
        'rating':' 3.6',
        'numberReviews': '156',

    },
    {
        'id': '8',
        'name': "EYEBOGLER Mens Cotton Regular Fit T-Shirt Grey",
        'image': '../../images/tshirt/ts_3.1.jpg' ,
        'description':" Care Instructions: Hand Wash Only Fit Type: Regular Fit Breathable Cotton Fabric",
        'brand': "EYEBOGLER",
        'categroy': "Tshirt" ,
        'price': '1299' ,
        'countInStock': '21',
        'rating': '3.2',
        'numberReviews': '111',

    },
    {
        'id': '9',
        'name': "Veirdo® Oversized Loose Baggy Fit Drop Shooulder Half Sleeves Pure Cotton Will Never Die Graphic Printed T-Shirt for Men",
        'image': '../../images/tshirt/ts_4.1.jpg' ,
        'description':"Care Instructions: Hand Wash Only Fit Type: Oversized Fit Fabric: Cotton Neckline: Crew Neck Sleeves: Half-slevees More comfortable for your classic everyday look.",
        'brand': "Veirdo",
        'categroy': "Tshirt" ,
        'price': '1199' ,
        'countInStock': '10',
        'rating': '4.0',
        'numberReviews': '134',

    },
    {
        'id': '10',
        'name': "Van Heusen Athleisure Men Polo T-Shirt - 100% Combed Cotton - Colour Fresh, Quick Dry, Ultra Soft",
        'image': '../../images/tshirt/ts_5.1.jpg' ,
        'description':"Care Instructions: Machine Wash Fit Type: Regular Fit Colour Fresh: The Colour Fresh technology keeps the fabric looking new for longer. Lab tested. Wicking: The fabric has wicking property which draws perspiration from the skin keeping the body cool, dry and comfortable. Ultra Soft: The fabric is extremely soft and comfortable, keeping you at ease for hours. 100% Combed Cotton: The combed cotton fabric construction makes the polo t-shirt super soft while improving the durability and breathability. Slim Fit: The polo t-shirt is framed in a Slim Fit that adds a sleek look while keeping you at ease. Pattern Type: Solid; Occasion Type: Casual; Lifestyle: Casual; Sleeve Type: Half Sleeve; Fit Type: Regular Fit; Sport Type: Golf",
        'brand': "Van Heusen",
        'categroy': "Tshirt" ,
        'price': '1149',
        'countInStock': '4',
        'rating': '4.0',
        'numberReviews': '1825',

    }

]

